stages:
    #- test
    - deploy

deploy:
    image: Node:18-alpine3.15
    stage: deploy
    script:
        chmod og= $ID_RSA
        apk update && apk add openssh-client
        ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_CICD_USER@$SERVER_ADDRESS "cd ~/Reiman_Garden; git pull"
    only:
        - main
